version: '3'
services:
  db_redis:
    build:
      context: redis
      dockerfile: ../docker/Redis/DockerFile
    ports:
      - "6379:6379"
    networks:
      - backend

  db_mongo:
    build:
      context: mongodb
      dockerfile: ../docker/Mongodb/DockerFile
    ports:
      - "27017:27017"
    networks:
      - backend

networks:
  backend:
    driver: bridge
